#!/bin/bash

NAME="watcher"
VERSION="1.0"
SCALA_VERSION="2.11"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JAR="$DIR/target/scala-$SCALA_VERSION/$NAME-assembly-$VERSION.jar"
THREADS=2

if ! [ -f "$JAR" ]; then
  echo "JAR file does not exist." >&2
  echo "Make sure you run \`sbt assembly\` to build the JAR executable." >&2
  exit 1
fi

JAVA_OPTS="-Dfile.encoding=UTF8 -Dscala.concurrent.context.minThreads=$THREADS -Dscala.concurrent.context.numThreads=$THREADS -Dscala.concurrent.context.maxThreads=$THREADS"
java $JAVA_OPTS -jar $JAR
